#!/usr/bin/env bash

chown frr:frr /var/run/frr
chmod 2755 /var/run/frr

if [ -r "/lib/lsb/init-functions" ]; then
        . /lib/lsb/init-functions
else
        log_success_msg() {
                echo "$@"
        }
        log_warning_msg() {
                echo "$@" >&2
        }
        log_failure_msg() {
                echo "$@" >&2
        }
fi

#source /usr/lib/frr/frrcommon.sh
#/usr/lib/frr/watchfrr $(daemon_list)

/usr/lib/frr/frrinit.sh start

while true
do
  if ! ip -6 route show default | grep -q "proto bgp"; then
    # Clear the BGP session softly to re-push the RIB to the kernel
    log_warning_msg "Could not find default route clearing BGP sessions"
    /usr/bin/vtysh -c "clear ip bgp * soft out"
    /usr/bin/vtysh -c "clear ipv6 bgp * soft out"
  fi

  sleep 60
done
